version: '3'

services:
  app:
    build:
      dockerfile: Dockerfile
    depends_on:
      - psql
  psql:
    image: postgres
    environment:
      - POSTGRES_PASSWORD="${DB_PASSWORD}"
      - POSTGRES_DB="${DB_NAME}"
      - POSTGRES_USER="${DB_USERNAME}"